disabled_rules:
  - type_body_length
  - file_length
excluded:
  - Pods
  - EosioSwift/Crypto
line_length: 200
identifier_name:
  min-length: 4
  max_length: 60
  excluded:
    - id
    - tx
    - trx